In [1]:
import chardet

with open("datasets/books_titles.csv", "rb") as f:
    result = chardet.detect(f.read(10000))  # Read first 10KB to guess encoding

print(result['encoding'])  # e.g., 'ISO-8859-1', 'windows-1252', etc.

ISO-8859-1

In [2]:
import pandas as pd

bx_books = pd.read_csv(
    "datasets/books_titles.csv",
    encoding='ISO-8859-1',
    delimiter=';',
    on_bad_lines='skip',
    quotechar='"'
)

bx_books.head()

/tmp/ipykernel_3538/3503544998.py:3: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  bx_books = pd.read_csv(

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...

In [3]:
books_rating=pd.read_csv("datasets/book_ratings.csv")
books_rating

        user_id        ISBN  rating
0        276725  034545104X     0.0
1        276726   155061224     5.0
2        276727   446520802     0.0
3        276729  052165615X     3.0
4        276729   521795028     6.0
...         ...         ...     ...
783068   189558   451184386     8.0
783069   189558   451184971     8.0
783070   189558   451187474     8.0
783071   189558   451210158     8.0
783072   189558   553295071     8.0

[783073 rows x 3 columns]

In [4]:
data=pd.merge(bx_books,books_rating,on="ISBN")
data

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L,user_id,rating
0,074322678X,Where You'll Find Me: And Other Stories,Ann Beattie,2002,Scribner,http://images.amazon.com/images/P/074322678X.0...,http://images.amazon.com/images/P/074322678X.0...,http://images.amazon.com/images/P/074322678X.0...,8,5.0
1,080652121X,Hitler's Secret Bankers: The Myth of Swiss Neu...,Adam Lebor,2000,Citadel Press,http://images.amazon.com/images/P/080652121X.0...,http://images.amazon.com/images/P/080652121X.0...,http://images.amazon.com/images/P/080652121X.0...,8,0.0
2,1552041778,Jane Doe,R. J. Kaiser,1999,Mira Books,http://images.amazon.com/images/P/1552041778.0...,http://images.amazon.com/images/P/1552041778.0...,http://images.amazon.com/images/P/1552041778.0...,8,5.0
3,1558746218,A Second Chicken Soup for the Woman's Soul (Ch...,Jack Canfield,1998,Health Communications,http://images.amazon.com/images/P/1558746218.0...,http://images.amazon.com/images/P/1558746218.0...,http://images.amazon.com/images/P/1558746218.0...,8,0.0
4,1558746218,A Second Chicken Soup for the Woman's Soul (Ch...,Jack Canfield,1998,Health Communications,http://images.amazon.com/images/P/1558746218.0...,http://images.amazon.com/images/P/1558746218.0...,http://images.amazon.com/images/P/1558746218.0...,3363,0.0
...,...,...,...,...,...,...,...,...,...,...
135825,1885203071,Asylum Earth,Charles Bragg,1994,Tuttle Pub,http://images.amazon.com/images/P/1885203071.0...,http://images.amazon.com/images/P/1885203071.0...,http://images.amazon.com/images/P/1885203071.0...,189334,9.0
135826,1894622332,Fiddling With Disaster: Clearing the Past,Ashley Macisaac,2003,Warwick,http://images.amazon.com/images/P/1894622332.0...,http://images.amazon.com/images/P/1894622332.0...,http://images.amazon.com/images/P/1894622332.0...,189334,0.0
135827,2856080979,Dictionary Des Locutions Et Expressions Couran,M Boudjedid Meyer,0,La Maison Du Dictionnaire,http://images.amazon.com/images/P/2856080979.0...,http://images.amazon.com/images/P/2856080979.0...,http://images.amazon.com/images/P/2856080979.0...,189334,10.0
135828,2890899551,Expressions populaires quÃ©bÃ©coises,Jean CotÃ©,1995,Editions Quebecor,http://images.amazon.com/images/P/2890899551.0...,http://images.amazon.com/images/P/2890899551.0...,http://images.amazon.com/images/P/2890899551.0...,189334,8.0
135829,3822896330,Roy Lichtenstein (Basic Series),Janis Hendrickson,1996,Benedikt Taschen Verlag,http://images.amazon.com/images/P/3822896330.0...,http://images.amazon.com/images/P/3822896330.0...,http://images.amazon.com/images/P/3822896330.0...,189334,10.0

In [5]:
average_ratings=pd.DataFrame(data.groupby("Book-Title")["rating"].mean())
average_ratings['No_of_people_rated']=pd.DataFrame(data.groupby("Book-Title")["rating"].count())
average_ratings

,rating,No_of_people_rated
Book-Title,,
"Earth Prayers From around the World: 365 Prayers, Poems, and Invocations for Honoring the Earth",6.600000,5
Final Fantasy Anthology: Official Strategy Guide (Brady Games),5.000000,4
Flight of Fancy: American Heiresses (Zebra Ballad Romance),8.000000,1
"Little Comic Shop of Horrors (Give Yourself Goosebumps, Book 17)",0.000000,1
Mystery Mile,0.000000,2
...,...,...
Ã?Â?berraschung am Valentinstag.,0.000000,1
Ã?Â?lpiraten.,0.000000,2
Ã?Â?rger mit Produkt X. Roman.,4.666667,3
Ã?Â?stlich der Berge.,8.000000,1
Ã?Â?thique en toc,4.000000,2

In [6]:
popular_books = average_ratings[average_ratings['No_of_people_rated'] > 100].index
filtered_data = data[data['Book-Title'].isin(popular_books)]

pivot = filtered_data.pivot_table(index='user_id', columns='Book-Title', values='rating')
pivot

Book-Title,"A Child Called \It\"": One Child's Courage to Survive""",A Fine Balance,A Painted House,About a Boy,All I Really Need to Know,Angela's Ashes: A Memoir,At Home in Mitford (The Mitford Years),Atonement : A Novel,Bag of Bones,"Breath, Eyes, Memory",...,The Kitchen God's Wife,The Lost Boy: A Foster Child's Search for the Love of a Family,The Lost World,The No. 1 Ladies' Detective Agency (Today Show Book Club #8),The Perfect Storm : A True Story of Men Against the Sea,The Rainmaker,The Stone Diaries,The Tale of the Body Thief (Vampire Chronicles (Paperback)),"Welcome to the World, Baby Girl!",What Looks Like Crazy On An Ordinary Day
user_id,,,,,,,,,,,,,,,,,,,,,
67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
176,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
243,NaN,NaN,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
244,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
254,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
278582,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,10.0,NaN,NaN,NaN,NaN,NaN,NaN
278633,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
278832,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
278843,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
278854,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
selected_book=pivot['Bag of Bones']
selected_book

similar=pivot.corrwith(selected_book)

similar_df=pd.DataFrame(similar,columns=['correlation'])
similar_df.sort_values("correlation",ascending=False).head(10)

/usr/lib/python3/dist-packages/numpy/lib/function_base.py:2889: RuntimeWarning: Degrees of freedom <= 0 for slice
  c = cov(x, y, rowvar, dtype=dtype)
/usr/lib/python3/dist-packages/numpy/lib/function_base.py:2748: RuntimeWarning: divide by zero encountered in divide
  c *= np.true_divide(1, fact)
/usr/lib/python3/dist-packages/numpy/lib/function_base.py:2748: RuntimeWarning: invalid value encountered in multiply
  c *= np.true_divide(1, fact)
/usr/lib/python3/dist-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/usr/lib/python3/dist-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]

                                                    correlation
Book-Title
Bag of Bones                                           1.000000
High Fidelity                                          1.000000
The Stone Diaries                                      1.000000
Night Sins                                             0.989239
Flesh and Blood                                        0.985632
The Color of Water: A Black Man's Tribute to Hi...     0.976497
The Lost World                                         0.931827
The Celestine Prophecy (Celestine Prophecy)            0.816497
Men Are from Mars, Women Are from Venus: A Prac...     0.812605
Welcome to the World, Baby Girl!                       0.743444

In [8]:
similar_books=similar_df.join(average_ratings['No_of_people_rated'])
similar_books

,correlation,No_of_people_rated
Book-Title,,
"A Child Called \It\"": One Child's Courage to Survive""",-0.429671,202
A Fine Balance,-0.495434,113
A Painted House,0.343543,570
About a Boy,NaN,121
All I Really Need to Know,0.513427,172
Angela's Ashes: A Memoir,-0.200000,155
At Home in Mitford (The Mitford Years),0.731126,149
Atonement : A Novel,NaN,115
Bag of Bones,1.000000,126
"Breath, Eyes, Memory",0.322501,128
Breathing Lessons,-0.077377,137
Bridget Jones's Diary,-0.481307,174
Call of the Wild,0.661438,120
Chicken Soup for the Soul (Chicken Soup for the Soul),0.507673,150
Dreamcatcher,0.725085,143
Face the Fire (Three Sisters Island Trilogy),0.645497,158
Flesh and Blood,0.985632,126
Full Tilt (Janet Evanovich's Full Series),NaN,107
Girl in Hyacinth Blue,0.420929,149
Hannibal,-1.000000,105
Harry Potter and the Order of the Phoenix (Book 5),-0.484949,220
Harry Potter and the Sorcerer's Stone (Harry Potter (Paperback)),0.075701,400
High Fidelity,1.000000,128
Hornet's Nest,-0.070569,123
How to Be Good,0.021320,198
"Men Are from Mars, Women Are from Venus: A Practical Guide for Improving Communication and Getting What You Want in Your Relationships",0.812605,105
Night Sins,0.989239,117
One True Thing,0.205350,131
Politically Correct Bedtime Stories: Modern Tales for Our Life and Times,0.418996,115
Running with Scissors: A Memoir,-0.016689,123
STONES FROM THE RIVER,0.058035,236
Snow Falling on Cedars,0.054341,433
Tears of the Giraffe (No.1 Ladies Detective Agency),0.071101,143
The Bridges of Madison County,-0.339913,254
The Celestine Prophecy (Celestine Prophecy),0.816497,138
The Color of Water: A Black Man's Tribute to His White Mother,0.976497,152
The Firm,-0.119625,362
The Four Agreements: A Practical Guide to Personal Freedom,0.654654,105
The Girls' Guide to Hunting and Fishing,-0.250000,112
The Hundred Secret Senses,0.574383,152
The Kitchen God's Wife,-0.043186,190
The Lost Boy: A Foster Child's Search for the Love of a Family,0.731126,115
The Lost World,0.931827,165
The No. 1 Ladies' Detective Agency (Today Show Book Club #8),NaN,290
The Perfect Storm : A True Story of Men Against the Sea,0.006681,251
The Rainmaker,0.139858,265
The Stone Diaries,1.000000,133
The Tale of the Body Thief (Vampire Chronicles (Paperback)),0.108091,124
"Welcome to the World, Baby Girl!",0.743444,140
What Looks Like Crazy On An Ordinary Day,0.013548,145